### ISSUE TITLE
Dynamic bitset compilation broken in boost 1.90.0?

### ISSUE THREAD

**Issue by bredelings** [boostorg/dynamic_bitset#100]
The `operator-` on bit iterators fails to compile in boost v1.90. Could I be missing something here?

```
template< typename Iterator >
BOOST_DYNAMIC_BITSET_CONSTEXPR20 std::ptrdiff_t
                                 operator-( const bit_iterator_base< Iterator > & lhs, const bit_iterator_base< Iterator > & rhs )
{
    return ( lhs.m_block_iterator - rhs.m_block_iterator ) * bit_iterator_base< Iterator >::bits_per_block
         + lhs.m_bit_index - rhs.m_bit_index;
}
```

The error for gcc-15 looks like:
```
`/path/to/installed-boost-1.90.0/include/boost/dynamic_bitset/impl/dynamic_bitset.ipp:247:18: error: ‘__gnu_cxx::__normal_iterator<const long unsigned int*, std::vector<long unsigned int> > boost::bit_iterator_base<__gnu_cxx::__normal_iterator<const long unsigned int*, std::vector<long unsigned int> > >::m_block_iterator’ is protected within this context
  247 |     return ( lhs.m_block_iterator - rhs.m_block_iterator ) * bit_iterator_base< Iterator >::bits_per_block
      |              ~~~~^~~~~~~~~~~~~~~~
...
```

I'm not getting errors on `operator==` and `operator<`, but it looks like they may have the same issue.

Could this be fixed for boost v1.90.1?

**Comment by bredelings** [comment]
I added the missing friend declaration and then I get:

```
/usr/include/c++/15/bits/stl_iterator_base_funcs.h:108:21: error: ambiguous overload for ‘operator-’ (operand types are ‘boost::const_bit_iterator<boost::dynamic_bitset<> >’ and ‘boost::const_bit_iterator<boost::dynamic_bitset<> >’)
  108 |       return __last - __first;
      |              ~~~~~~~^~~~~~~~~
/usr/include/c++/15/bits/stl_iterator_base_funcs.h:108:21: note: there are 2 candidates
In file included from /usr/include/boost/dynamic_bitset.hpp:15,
                 from ../../jj/src/core/datatypes/RbVector.h:10,
                 from ../../jj/src/core/statistics/tree/TreeBipartitions.h:10:
/usr/include/boost/dynamic_bitset/dynamic_bitset.hpp:1444:50: note: candidate 1: ‘constexpr bool boost::operator-(const bit_iterator_base<Iter>&, const bit_iterator_base<Iter>&) [with Iter = __gnu_cxx::__normal_iterator<const long unsigned int*, std::vector<long unsigned int> >; Iterator = __gnu_cxx::__normal_iterator<long unsigned int*, std::vector<long unsigned int> >]’
 1444 |     friend BOOST_DYNAMIC_BITSET_CONSTEXPR20 bool operator-( const bit_iterator_base< Iter > & lhs, const bit_iterator_base< Iter > & rhs );
      |                                                  ^~~~~~~~
In file included from /usr/include/boost/dynamic_bitset/dynamic_bitset.hpp:1788:
/usr/include/boost/dynamic_bitset/impl/dynamic_bitset.ipp:245:34: note: candidate 2: ‘constexpr std::ptrdiff_t boost::operator-(const bit_iterator_base<Iterator>&, const bit_iterator_base<Iterator>&) [with Iterator = __gnu_cxx::__normal_iterator<const long unsigned int*, std::vector<long unsigned int> >; std::ptrdiff_t = long int]’
  245 |                                  operator-( const bit_iterator_base< Iterator > & lhs, const bit_iterator_base< Iterator > & rhs )
      |                                  ^~~~~~~~
```

**Comment by gennaroprota** [comment]
That's odd. CI is passing on both master and develop. Which compiler are you using? I guess that's GCC 15, which we test with.

**Comment by bredelings** [comment]
I am sorry -- I had a typo.  1.90 works fine with just that one-line change.

I also checked 1.91-beta1, and it also works fine.
